require("config.telescope")
require("config.devicons")
require("config.treesiter")
require("config.lsp")
require("config.saga")
require("config.gitsigns")
require("config.galaxy")
-- lua print(vim.env.VIRTUAL_ENV:match("^.+/(.+)$"))
