require("config.devicons")
require("config.treesiter")
require("config.lsp")
require("config.compe")
require("config.kind")
require("config.gitsigns")
require("config.galaxy")
-- require("config.dap")
-- require('spellsitter').setup()
-- require('nvim-projectconfig').load_project_config()
require('config.trouble')
require("config.telescope")
require('Comment').setup()
