source $HOME/.dotfiles/vim/plugins.vim
source $HOME/.dotfiles/vim/general.vim
source $HOME/.dotfiles/vim/theme.vim

lua require("config")

source $HOME/.dotfiles/vim/plug-config/autoformat.vim
source $HOME/.dotfiles/vim/plug-config/easyclip.vim
source $HOME/.dotfiles/vim/plug-config/maximizer.vim
source $HOME/.dotfiles/vim/plug-config/mbe.vim
source $HOME/.dotfiles/vim/plug-config/nerdtree.vim
source $HOME/.dotfiles/vim/plug-config/quickscope.vim
source $HOME/.dotfiles/vim/plug-config/suda.vim
source $HOME/.dotfiles/vim/plug-config/tablemode.vim
source $HOME/.dotfiles/vim/plug-config/tabular.vim
source $HOME/.dotfiles/vim/plug-config/vimtest.vim
source $HOME/.dotfiles/vim/plug-config/vimwiki.vim
source $HOME/.dotfiles/vim/plug-config/vista.vim
source $HOME/.dotfiles/vim/plug-config/gittimelapse.vim
source $HOME/.dotfiles/vim/plug-config/tmux_navigator.vim
