#! /bin/sh

setxkbmap -option caps:ctrl_modifier
killall sxhkd
sxhkd $HOME/.config/bspwm/sxhkdrc $HOME/.config/bspwm/sxhkdrc_normal &

if [ -z $_laptop ] ; then
    _lock_timer=120
else
    xinput set-prop 'Synaptics TM3512-010' 'libinput Tapping Enabled' 1
    xinput set-prop 'Synaptics TM3512-010' 'libinput Natural Scrolling Enabled' 1
fi


bspc config border_width         2
bspc monitor "$_bspwm_first_screen" -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a Slack desktop=^9 focus=on
bspc rule -a slack desktop=^9 focus=on
bspc rule -a Evolution desktop=^9 focus=on
bspc rule -a Thunderbird desktop=^10 focus=on
bspc rule -a "Cisco AnyConnect Secure Mobility Client" state=floating center=on desktop=^10
bspc rule -a "microsoft teams - preview" desktop=^8

bspc rule -a spotify desktop=^4 focus=on

