#! /bin/sh

setxkbmap -option caps:ctrl_modifier

xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Natural Scrolling Enabled' 1
xsetroot -cursor_name left_ptr

feh --bg-scale $HOME/.dotfiles/resources/wallpaper/wallpaper5.jpg &
xrdb ~/.Xresources

$HOME/.config/polybar/launch_polybar.sh

killall mate-power-manager
mate-power-manager &

killall dunst
dunst &

killall sxhkd
sxhkd $HOME/.config/bspwm/sxhkdrc &

killall compton
compton &

killall unclutter
unclutter &

killall nm-applet
nm-applet &
# killall libinput-gestures
# libinput-gestures &
evolution &
slack &

.dotfiles/bin/i3locker &


bspc monitor HDMI-1 -d 1 2 3 4 5
bspc monitor HDMI-2 -d 6 7 8 9 10

bspc config border_width         4
bspc config normal_border_color "#002b36"
bspc config window_gap           10
bspc config top_padding          0
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle      true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Chromium desktop='^2'
bspc rule -a Evolution desktop='^10' focus=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Slack desktop='^9' focus=on
bspc rule -a Packman state=floating center=on
