#! /bin/sh

setxkbmap -option caps:ctrl_modifier
killall sxhkd
sxhkd $HOME/.config/bspwm/sxhkdrc $HOME/.config/bspwm/sxhkdrc_inverse &

if [ -z $_laptop ] ; then
    _lock_timer=120
else
    xinput set-prop 'Synaptics TM3512-010' 'libinput Tapping Enabled' 1
    xinput set-prop 'Synaptics TM3512-010' 'libinput Natural Scrolling Enabled' 1
fi

bspc config border_width 2

bspc monitor "$_bspwm_first_screen" -d 6 7 8 9 10
bspc monitor "$_bspwm_dot_second_screen" -d 1 2 3 4 5

bspc rule -a Evolution desktop=^5 focus=on
bspc rule -a Slack desktop=^5 focus=on
bspc rule -a slack desktop=^5 focus=on
bspc rule -a "microsoft teams - preview" desktop=^3 focus=on
bspc rule -a "Microsoft Teams - Preview" desktop=^3 focus=on
bspc rule -a 'Cisco AnyConnect Secure Mobility Client' state=floating center=on desktop=^4

