#!/bin/python3

import os
from subprocess import getoutput

button = os.environ.get('BLOCK_BUTTON', None)

if button == '1':
    getoutput('xkblayout-state set +1')

try:
    layouts = int(getoutput(r'xkblayout-state print %C'))
except Exception:
    layout = 0


if layouts > 1:
    layout = getoutput(r'xkblayout-state print %s')
    print(': {}'.format(layout))


