#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export TERM=screen-256color
export PATH="$HOME/.local/bin:$HOME/bin:$PATH"

vim()
{
	# Save current stty options.
	local STTYOPTS="$(stty -g)"

	# Disable intercepting of ctrl-s and ctrl-q as flow control.
	stty stop '' -ixoff -ixon

	# Execute vim.
	vim_command "$@"

	# Restore saved stty options.
	stty "$STTYOPTS"
}

vim_command()
{
	if (( $+commands[reattach-to-user-namespace] )); then
	# See: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
	command reattach-to-user-namespace vim "$@"
	else
	command vim "$@"
	fi
}

alias tmux="TERM=xterm-256color tmux -2"

if [[ `uname` != 'Darwin' ]]; then
	eval `dircolors ~/.dotfiles/resources/dircolors-solarized/dircolors.ansi-dark`
fi


export LC_CTYPE=en_US.UTF-8

export PYENV_ROOT="$HOME/.pyenv"

if which virtualenvwrapper.sh > /dev/null; then
    . $(which virtualenvwrapper.sh);
fi

if [ -d $PYENV_ROOT ]; then
    export PATH="$HOME/.pyenv/bin:$PATH";
    eval "$(pyenv init -)";
    pyenv virtualenvwrapper;
fi
