-- Generated by Monique - https://github.com/ToRvaLDz/monique

hl.monitor({
  output = "DP-2",
  mode = "1920x1200@59.95",
  position = "1343x-183",
  scale = 1,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "DP-2", default = true, persistent = true, })
hl.workspace_rule({ workspace = "2", monitor = "DP-2", })
hl.workspace_rule({ workspace = "3", monitor = "DP-2", })
hl.workspace_rule({ workspace = "4", monitor = "DP-2", })
hl.workspace_rule({ workspace = "5", monitor = "DP-2", })
hl.workspace_rule({ workspace = "6", monitor = "HDMI-A-2", default = true, persistent = true, })
hl.workspace_rule({ workspace = "7", monitor = "HDMI-A-2", })
hl.workspace_rule({ workspace = "8", monitor = "HDMI-A-2", })
hl.workspace_rule({ workspace = "9", monitor = "HDMI-A-2", })
hl.workspace_rule({ workspace = "10", monitor = "HDMI-A-2", })
