#!/bin/sh

[ -z "$1" ] && exit

inst=dropdown_$1;

case $1 in
   tmux*)
       cmd="tmux a -t $inst || tmux new -s $inst"
       exe="termite --name $inst -e $cmd"
       ;;
   nautilus)
       exe="nautilus --name $inst"
       ;;
   *) exit
esac

if xwininfo -tree -root | grep $inst ;
then
	i3-msg "[instance=\"$inst\"] scratchpad show; [instance=\"$inst\"] move position center"
else
    i3-msg "exec --no-startup-id $exe"
fi
