#!/usr/bin/env sh

# This script sets the statusbar with the xsetroot command at the end. Have it
# started by ~/.xinitrc or ~/.xprofile.

# Handle SIGTRAP signals sent by refbar to update the status bar immediately.
trap 'update' 5

# Set the deliminter character.
delim="|"

# Here is the (big) function that outputs the appearance of the statusbar. It
# can really be broken down into many submodules which I've commented and
# explained.
status() { \

	# Get current mpd track filename or artist - title if possible.
    # echo `~/.dotfiles/i3scripts/statusbar/mediaplayer`

    echo "$delim"

    echo `~/.dotfiles/i3scripts/statusbar/kb_layout`

    echo "$delim"

    echo `~/.dotfiles/i3scripts/statusbar/volume`

	echo "$delim"

	# Date and time.
	date '+%Y %b %d (%a) %I:%M%p'
	}

update() { \
	# So all that big status function was just a command that quicking gets
	# what we want to be the statusbar. This xsetroot command is what sets
	# it. Note that the tr command replaces newlines with spaces. This is
	# to prevent some weird issues that cause significant slowing of
	# everything in dwm. Note entirely sure of the cause, but again, the tr
	# command easily avoids it.
	xsetroot -name "$(status | tr '\n' ' ')" &
    wait

    }


while :; do
    # update
    xsetroot -name "$(status | tr '\n' ' ')" &
	# Sleep for a minute after changing the status bar before updating it
	# again. We run sleep in the background and use wait until it finishes,
    # because traps can interrupt wait immediately, but they can't do that
    # with sleep.
	sleep 1min &
    wait
done
