#!/bin/bash

notify-send 'reboot called'
res=$(echo -e "shutdown\nreboot\nlogout" | rofi -dmenu)

if [ $res = "logout" ]; then
    i3-msg exit
fi
if [ $res = "reboot" ]; then
    reboot
fi
if [ $res = "shutdown" ]; then
    shutdown -h now
fi
exit 0
