export DOTDIR=$HOME/.dotfiles
export ZDOTDIR=$DOTDIR/zsh
export DOT_BIN=$DOTDIR/bin
export PATH="$DOT_BIN:$PATH"
export TERMINAL=alacritty
export XDG_CONFIG_HOME="$HOME/.config"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

if [[ -n $VIRTUAL_ENV && -e "${VIRTUAL_ENV}/bin/activate" ]]; then
  source "${VIRTUAL_ENV}/bin/activate"
fi
