
[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Y"
mods = "Control|Shift"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 6
y = 6

[general]

live_config_reload = true
import = [
    "~/.config/alacritty/fonts.toml",
    # "~/.config/alacritty/onedark.toml",
    # "~/.config/alacritty/catppuccin-latte.toml",
    # "~/.config/alacritty/catppuccin-frappe.toml",
    "~/.config/alacritty/catppuccin-macchiato.toml",
    # "~/.config/alacritty/catppuccin-mocha.toml"
]
